apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifest:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: kamilkodzi/client
      contex: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: kamilkodzi/comments
      contex: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: kamilkodzi/event-bus
      contex: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: kamilkodzi/moderation
      contex: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: kamilkodzi/posts
      contex: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: kamilkodzi/query
      contex: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .